(()=>{'use strict';
const DB='vn2-launcher', STORE='state', MANIFEST='version.json';
const MAGIC='RV19T', AAD=new TextEncoder().encode('REHA-Vertragsmanager-v19-pages-targz');
const $=id=>document.getElementById(id);
const el={teamsBadge:$('teamsBadge'),connectFolder:$('connectFolder'),reauthorizeFolder:$('reauthorizeFolder'),checkUpdate:$('checkUpdate'),folderHint:$('folderHint'),updatePanel:$('updatePanel'),updateTitle:$('updateTitle'),updateText:$('updateText'),progress:$('progress'),progressBar:$('progressBar'),progressText:$('progressText'),cachedPanel:$('cachedPanel'),cachedInfo:$('cachedInfo'),openCached:$('openCached'),manualFiles:$('manualFiles'),manualFileList:$('manualFileList'),accessKey:$('accessKey'),setupManual:$('setupManual'),detailPanel:$('detailPanel'),detailKv:$('detailKv'),errorPanel:$('errorPanel'),errorText:$('errorText')};
let dir=null, selection=null, active=null, deviceKey=null, busy=false;
const err=m=>{el.errorText.textContent=m;el.errorPanel.classList.remove('hidden')};
const clear=()=>{el.errorPanel.classList.add('hidden');el.errorText.textContent=''};
const prog=(show,p=0,t='')=>{el.progress.classList.toggle('hidden',!show);el.progressBar.style.width=Math.max(0,Math.min(100,p))+'%';el.progressText.textContent=t};
const update=(title,text,kind='')=>{el.updatePanel.className='panel'+(kind?' '+kind:'');el.updatePanel.classList.remove('hidden');el.updateTitle.textContent=title;el.updateText.textContent=text};
const fmt=n=>{if(!Number.isFinite(n))return'–';const u=['B','KB','MB','GB'];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return `${v.toLocaleString('de-DE',{maximumFractionDigits:i?1:0})} ${u[i]}`};
const cleanPath=p=>String(p||'').replace(/^\.\//,'').replace(/^\/+/, '');
const safe=v=>String(v||'unknown').replace(/[^A-Za-z0-9._-]+/g,'_').slice(0,80)||'unknown';
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const basePath=()=>location.pathname.replace(/[^/]*$/,'');
const runtimeUrl=(ver,path,sha)=>`${location.origin}${basePath()}runtime/${safe(ver)}-${String(sha).slice(0,12)}/${cleanPath(path).split('/').map(encodeURIComponent).join('/')}`;
const mime=p=>({html:'text/html;charset=utf-8',js:'text/javascript;charset=utf-8',css:'text/css;charset=utf-8',json:'application/json;charset=utf-8',txt:'text/plain;charset=utf-8',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',svg:'image/svg+xml',pdf:'application/pdf',woff:'font/woff',woff2:'font/woff2'})[(p.split('.').pop()||'').toLowerCase()]||'application/octet-stream';
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbGet(k){const d=await openDb();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbSet(k,v){const d=await openDb();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function decodeAccessKey(value){let s=String(value||'').trim().replace(/\s+/g,'');if(!s)throw new Error('Bitte den Zugangsschlüssel eingeben.');if(/^[A-Fa-f0-9]{64}$/.test(s))throw new Error('Das sieht nach einer 64-stelligen SHA-256-Prüfsumme aus, nicht nach dem Zugangsschlüssel. Bitte den 43/44-stelligen Base64URL-Schlüssel aus der Datei „REHA-v19.3-Zugangsschluessel.txt“ verwenden.');if(!/^[A-Za-z0-9_-]+={0,2}$/.test(s))throw new Error('Der Zugangsschlüssel enthält ungültige Zeichen. Erwartet wird Base64URL.');const original=s;s=s.replace(/-/g,'+').replace(/_/g,'/').replace(/=+$/,'');s+='='.repeat((4-s.length%4)%4);let raw;try{raw=Uint8Array.from(atob(s),c=>c.charCodeAt(0))}catch{throw new Error('Der Zugangsschlüssel ist nicht korrekt Base64URL-codiert.')}if(raw.byteLength!==32)throw new Error(`Der Zugangsschlüssel ist nicht der richtige VN-Schlüssel: ${original.length} Zeichen ergeben ${raw.byteLength} Bytes. Erwartet werden 32 Bytes (typisch 43 Base64URL-Zeichen ohne Padding).`);return raw}
const importKey=raw=>crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['decrypt']);
const sha256=async bytes=>hex(await crypto.subtle.digest('SHA-256',bytes));
async function decrypt(bytes,key){if(bytes.byteLength<34)throw new Error('Datenpaket ist zu klein oder beschädigt.');if(new TextDecoder().decode(bytes.slice(0,5))!==MAGIC)throw new Error('Unbekanntes Datenpaket-Format.');const iv=bytes.slice(5,17);try{return await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:AAD,tagLength:128},key,bytes.slice(17))}catch{throw new Error('Entschlüsselung fehlgeschlagen. Zugangsschlüssel und Datenpaket passen nicht zusammen.')}}
function parseManifest(m){if(!m||typeof m!=='object')throw new Error('version.json ist ungültig.');for(const k of ['version','file','sha256'])if(!m[k])throw new Error(`version.json enthält kein Feld „${k}“`);if(!/^[a-f0-9]{64}$/i.test(m.sha256))throw new Error('SHA-256 in version.json ist ungültig.');if(!String(m.file).toLowerCase().endsWith('.enc'))throw new Error('version.json verweist nicht auf eine .enc-Datei.');return m}
async function manifestFromDir(h){const f=await (await h.getFileHandle(MANIFEST)).getFile();return parseManifest(JSON.parse(await f.text()))}
async function packageFromDir(h,m){return (await h.getFileHandle(m.file)).getFile()}
class StreamReader{constructor(r){this.r=r;this.q=[];this.off=0;this.avail=0;this.done=false}async fill(n){while(this.avail<n&&!this.done){const {value,done}=await this.r.read();if(done){this.done=true;break}if(value?.byteLength){this.q.push(value);this.avail+=value.byteLength}}if(this.avail<n)throw new Error('Archiv ist unerwartet zu Ende.')}async read(n){if(!n)return new Uint8Array();await this.fill(n);const out=new Uint8Array(n);let p=0;while(p<n){const c=this.q[0],take=Math.min(c.byteLength-this.off,n-p);out.set(c.subarray(this.off,this.off+take),p);p+=take;this.off+=take;this.avail-=take;if(this.off>=c.byteLength){this.q.shift();this.off=0}}return out}}
const tarStr=(b,s,l)=>{let e=s;while(e<s+l&&b[e]!==0)e++;return new TextDecoder().decode(b.subarray(s,e)).trim()};
const tarOct=(b,s,l)=>parseInt(tarStr(b,s,l).replace(/\0/g,'').trim()||'0',8)||0;
const zeros=b=>b.every(x=>x===0);
async function extractTarGz(gzip,m){if(typeof DecompressionStream==='undefined')throw new Error('Bitte aktuellen Edge oder Chrome verwenden.');const ds=new Blob([gzip]).stream().pipeThrough(new DecompressionStream('gzip'));const sr=new StreamReader(ds.getReader()),cacheName=`vn-runtime-${safe(m.version)}-${m.sha256.slice(0,12)}`,cache=await caches.open(cacheName);let count=0,total=0,hasIndex=false;try{while(true){const h=await sr.read(512);if(zeros(h))break;let name=tarStr(h,0,100),prefix=tarStr(h,345,155);if(prefix)name=prefix+'/'+name;name=cleanPath(name);const size=tarOct(h,124,12),type=String.fromCharCode(h[156]||48);if(type==='0'||type==='\0'){const data=await sr.read(size),pad=(512-(size%512))%512;if(pad)await sr.read(pad);if(name&&name!=='.'){await cache.put(runtimeUrl(m.version,name,m.sha256),new Response(data,{headers:{'Content-Type':mime(name),'Cache-Control':'no-store'}}));count++;total+=size;if(name==='index.html')hasIndex=true}}else{if(size)await sr.read(size);const pad=(512-(size%512))%512;if(pad)await sr.read(pad)}}if(!hasIndex)throw new Error('Archiv enthält keine index.html.');return {cacheName,count,total,entryUrl:runtimeUrl(m.version,'index.html',m.sha256)}}catch(e){await caches.delete(cacheName);throw e}}
async function permission(h,ask=false){if(!h?.queryPermission)return'unsupported';let p=await h.queryPermission({mode:'read'});if(p!=='granted'&&ask&&h.requestPermission)p=await h.requestPermission({mode:'read'});return p}
async function saveKey(key){try{await dbSet('cryptoKey',key);deviceKey=key;return true}catch{return false}}
async function processVersion(m,file,key,source){if(busy)return;busy=true;clear();try{update('Update wird geprüft',`${m.version} aus ${source}`);prog(true,10,'Datenpaket wird gelesen …');const buf=await file.arrayBuffer();prog(true,25,`${fmt(buf.byteLength)} · SHA-256 wird geprüft …`);const got=await sha256(buf);if(got.toLowerCase()!==m.sha256.toLowerCase())throw new Error(`Prüfsumme stimmt nicht. Erwartet ${m.sha256}, erhalten ${got}.`);prog(true,42,'Prüfsumme korrekt · Paket wird entschlüsselt …');const plain=await decrypt(buf,key);prog(true,60,'Entschlüsselung erfolgreich · Runtime wird aufgebaut …');const rt=await extractTarGz(plain,m);const next={version:m.version,sha256:m.sha256,file:m.file,date:m.date||'',cacheName:rt.cacheName,entryUrl:rt.entryUrl,installedAt:new Date().toLocaleString('de-DE'),source,files:rt.count,total:rt.total};await dbSet('activeRuntime',next);active=next;for(const k of await caches.keys())if(k.startsWith('vn-runtime-')&&k!==rt.cacheName)await caches.delete(k);navigator.storage?.persist?.().catch(()=>false);prog(true,100,`${rt.count} Dateien · ${fmt(rt.total)} · Update erfolgreich.`);update('Datenstand bereit',`${m.version} wurde vollständig geprüft und lokal aktiviert.`,'ok');render()}catch(e){update('Update nicht aktiviert','Die zuletzt funktionierende Version bleibt erhalten.','bad');err(e.message||String(e))}finally{busy=false}}
async function keyForOperation(requireInput=false){const input=el.accessKey.value.trim();if(input)return importKey(decodeAccessKey(input));if(deviceKey&&!requireInput)return deviceKey;throw new Error('Bitte den Zugangsschlüssel einmal eingeben.')}
function selectFiles(files){const a=[...files],mf=a.find(f=>f.name.toLowerCase()==='version.json'),ef=a.find(f=>f.name.toLowerCase().endsWith('.enc'));selection={mf,ef};el.manualFileList.textContent=a.length?a.map(f=>`${f.name} · ${fmt(f.size)}`).join(' | '):''}
async function manualSetup(){clear();try{const key=await keyForOperation(true);let m,file,source='manuelle Einrichtung';if(selection?.mf&&selection?.ef){m=parseManifest(JSON.parse(await selection.mf.text()));if(selection.ef.name!==m.file)throw new Error(`version.json erwartet „${m.file}“, ausgewählt wurde „${selection.ef.name}“.`);file=selection.ef}else if(dir){if(await permission(dir,true)!=='granted')throw new Error('Keine Leseberechtigung für den Teams-Ordner.');m=await manifestFromDir(dir);file=await packageFromDir(dir,m);source=`Teams/${dir.name}`}else throw new Error('Bitte Teams-Ordner verbinden oder version.json und .enc gemeinsam auswählen.');if(await processVersion(m,file,key,source)){await saveKey(key);el.accessKey.value=''}}catch(e){err(e.message||String(e))}}
async function checkUpdates(user=false,ask=false){clear();if(!dir){if(user)err('Noch kein Teams-Ordner verbunden.');return}if(await permission(dir,ask)!=='granted'){el.teamsBadge.textContent='Berechtigung nötig';el.reauthorizeFolder.classList.remove('hidden');el.checkUpdate.disabled=true;return}el.reauthorizeFolder.classList.add('hidden');el.checkUpdate.disabled=false;try{const m=await manifestFromDir(dir);if(active?.sha256===m.sha256){update('Datenstand aktuell',`${m.version} entspricht der zuletzt erfolgreich geprüften Version.`,'ok');return}update('Datenupdate erforderlich',`${m.version} ist verfügbar.`,'warn');if(deviceKey){const f=await packageFromDir(dir,m);await processVersion(m,f,deviceKey,`Teams/${dir.name}`)}else if(user)err('Update gefunden. Bitte einmal den Zugangsschlüssel eingeben und „Gerät einrichten / Datenstand prüfen“ verwenden.')}catch(e){err(`Teams-Ordner konnte nicht gelesen werden: ${e.message||e}`)}}
async function connectFolder(){clear();if(!window.showDirectoryPicker){err('Ordnerfreigabe wird nicht unterstützt. Bitte aktuellen Microsoft Edge oder Chrome verwenden.');return}try{dir=await window.showDirectoryPicker({mode:'read'});await dbSet('directoryHandle',dir);el.folderHint.textContent=`Verbunden: ${dir.name}. Erwartet werden version.json und die darin genannte .enc-Datei.`;render();await checkUpdates(true,true)}catch(e){if(e.name!=='AbortError')err(e.message||String(e))}}
function render(){if(active){el.cachedPanel.classList.remove('hidden');el.cachedInfo.textContent=`${active.version} · geprüft ${active.installedAt||''} · SHA-256 ${String(active.sha256||'').slice(0,16)}…`;el.openCached.disabled=false}else el.cachedPanel.classList.add('hidden');if(dir){el.teamsBadge.textContent='verbunden';el.connectFolder.textContent='Teams-Ordner wechseln';el.checkUpdate.disabled=false}else{el.teamsBadge.textContent='nicht verbunden';el.checkUpdate.disabled=true}const rows=[['Ordnerfreigabe',dir?.name||'–'],['Geräteschlüssel',deviceKey?'ja':'nein'],['Aktive Runtime',active?.version||'–'],['Aktiver SHA-256',active?.sha256||'–'],['Service Worker','serviceWorker'in navigator?'unterstützt':'nicht unterstützt']];el.detailKv.innerHTML=rows.map(([a,b])=>`<b>${a}</b><span>${String(b)}</span>`).join('');el.detailPanel.classList.remove('hidden')}
function openRuntime(){if(!active?.entryUrl)return err('Keine verifizierte lokale Version vorhanden.');location.href=active.entryUrl+`?vn=${encodeURIComponent(active.version)}`}
async function init(){try{if(!('serviceWorker'in navigator))throw new Error('Service Worker werden von diesem Browser nicht unterstützt.');await navigator.serviceWorker.register('./sw.js?v=2',{scope:'./',updateViaCache:'none'});await navigator.serviceWorker.ready}catch(e){err('Launcher-Service-Worker konnte nicht aktiviert werden: '+(e.message||e))}try{dir=await dbGet('directoryHandle')||null;active=await dbGet('activeRuntime')||null;deviceKey=await dbGet('cryptoKey')||null}catch{}render();if(dir){const p=await permission(dir);if(p==='granted'||p==='unsupported')setTimeout(()=>checkUpdates(false,false),300);else{el.teamsBadge.textContent='Berechtigung nötig';el.reauthorizeFolder.classList.remove('hidden');el.checkUpdate.disabled=true}}}
el.connectFolder.addEventListener('click',connectFolder);el.reauthorizeFolder.addEventListener('click',async()=>{if(await permission(dir,true)==='granted'){render();el.reauthorizeFolder.classList.add('hidden');await checkUpdates(true,false)}});el.checkUpdate.addEventListener('click',()=>checkUpdates(true,true));el.manualFiles.addEventListener('change',e=>selectFiles(e.target.files));el.setupManual.addEventListener('click',manualSetup);el.openCached.addEventListener('click',openRuntime);init();
})();
